### ISSUE TITLE
Store hash-version map files for acquiring version number

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1312]
**Required skills**: Python

**Difficulty**: Easy

**Motivation**

Age of Empires 2 and other Genie games do not store their version number in a plaintext file or anything else that is easy to read. Therefore, openage uses the hashes of files to determine the version of a game. The idea behind this is that a file from a specific release will always have the same hash value. By calculating the hash for a file and looking up the hash in a dict of hash values and version numbers, we can find the release version the file belongs to.

**Task**

The dicts of hashes and version numbers should ideally be stored in a config file. TOML can be used as a format since we already use that elsewhere in the converter. There should be one config file for every game edition and game expansion.

Example (using TOML):

```toml
# Header
# The version of this config file format
file_version = "1.0"
hash_algo = "SHA3-256"

[empires2dat]
path = "Data/empires2.dat"

    [empires2dat.map]
    "d45b001ee8493c1c61a1" = "1.0"
    "4239b6d45b001ee38128" = "1.2"


[age2_x1]
path = "age2_x1/age2_x1.exe"

    [age2_x1.map]
    "001ee8493c1c61a1d45b" = "1.0"
    "b001ee381284239b6d45" = "1.2"
```

Every file that we want to hash should get its own table with a subtable for the hash-version map. The recommended hashing algorithms are SHA3-256 or SHA-512.
