### ISSUE TITLE
Store game edition and game expansion info in auxiliary file instead of hardcoding it

### ISSUE THREAD

**Issue by heinezen** [SFTtech/openage#1314]
**Required skills**: Python

**Difficulty**: Easy

openage currently stores information about a game edition or expansion inside an `Enum`, e.g. media paths, support status, etc. We should store this information in an auxiliary file instead, similar to #1312. That would make updating and correcting game information easier as we no longer have to replace chunks of code.

The recommended approach is to transfer the information from the existing implementation into a simple data definition file format. TOML is prefered because we already use that elsewhere in the converter.

Example:

```toml
# Header
# The version of this config file format
file_version = "1.0"

# Game edition info
game_edition_id = "AOC"
support_status = True

[media_paths]
datfile = [ "data/empires2.dat", ]
graphics = [ "data/graphics.drs", ]
palettes = [ "data/interfac.drs", ]
```

Since we cannot use Enums when we read the game versions from file, we would have to replace identity checks of the game version `Enum` value with an ID check. These checks happen when reading the `.dat` format or in the service that acquires nyan object names. They should be easy to replace.

**Further Reading**

* [GameVersion(Enum) implementation](https://github.com/SFTtech/openage/blob/master/openage/convert/value_object/init/game_version.py)
